name: .NET

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal 
    - name: Dotnet Pack ModbusTcp
      working-directory: ModbusTcp
      run: dotnet pack -c Release -p:Version=${GITHUB_REF##*/v}   
    - name: Dotnet Nuget Push ModbusTcp
      working-directory: ModbusTcp/bin/Release
      run: dotnet nuget push ModbusTcp.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      continue-on-error: true
